/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author COMP
 */
public class TelaDiagnostico extends javax.swing.JFrame {

    /**
     * Creates new form TelaDiagnostico
     */
    public TelaDiagnostico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtmensagem = new javax.swing.JLabel();
        txtSintoma = new javax.swing.JLabel();
        btnSim = new javax.swing.JButton();
        btnNao = new javax.swing.JButton();
        imagemdiagnostico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtmensagem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtmensagem.setText("Escolha \"Sim\" ou \"Não\" para os Seguinte sintomas");
        getContentPane().add(txtmensagem);
        txtmensagem.setBounds(60, 0, 410, 72);

        txtSintoma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSintoma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSintoma.setText("Sintoma");
        getContentPane().add(txtSintoma);
        txtSintoma.setBounds(80, 70, 370, 50);

        btnSim.setText("SIM");
        getContentPane().add(btnSim);
        btnSim.setBounds(170, 180, 100, 40);

        btnNao.setText("NÃO");
        getContentPane().add(btnNao);
        btnNao.setBounds(290, 180, 100, 40);

        imagemdiagnostico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundodiagnostico.jpg"))); // NOI18N
        getContentPane().add(imagemdiagnostico);
        imagemdiagnostico.setBounds(-60, 0, 590, 270);

        setSize(new java.awt.Dimension(518, 281));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDiagnostico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNao;
    private javax.swing.JButton btnSim;
    private javax.swing.JLabel imagemdiagnostico;
    private javax.swing.JLabel txtSintoma;
    private javax.swing.JLabel txtmensagem;
    // End of variables declaration//GEN-END:variables
}
